const catalogPages = [
  [1,'overview','产品手册封面','Product manual cover'],
  [2,'overview','福田汽车公司介绍','FOTON company introduction'],
  [3,'overview','产品手册目录','Manual contents'],
  [4,'overview','AUTOMATE 品牌介绍','AUTOMATE brand introduction'],
  [5,'overview','六大产品类别介绍（一）','Six product categories (I)'],
  [6,'overview','六大产品类别介绍（二）','Six product categories (II)'],
  [7,'maintenance','保养件','Maintenance parts'],
  [8,'maintenance','油品系列 - 产品特点与规格','Oil products - features and specifications'],
  [9,'maintenance','油品系列 - 产品明细（一）','Oil products - details (I)'],
  [10,'maintenance','油品系列 - 产品明细（二）','Oil products - details (II)'],
  [11,'maintenance','油品系列 - 产品明细（三）','Oil products - details (III)'],
  [12,'maintenance','冷却液系列 - 特点与产品明细','Coolant series - features and details'],
  [13,'maintenance','滤芯系列 - 产品特点','Filter element series - features'],
  [14,'maintenance','滤芯系列 - 产品明细（一）','Filter element series - details (I)'],
  [15,'maintenance','滤芯系列 - 产品明细（二）','Filter element series - details (II)'],
  [16,'maintenance','滤芯系列 - 产品明细（三）','Filter element series - details (III)'],
  [17,'maintenance','滤芯系列 - 产品明细（四）','Filter element series - details (IV)'],
  [18,'maintenance','滤芯系列 - 产品明细（五）','Filter element series - details (V)'],
  [19,'maintenance','滤芯系列 - 产品明细（六）','Filter element series - details (VI)'],
  [20,'wear','易损件','Wear parts'],
  [21,'wear','轮胎系列 - 产品特点','Tire products - features'],
  [22,'wear','轮胎系列 - 产品明细','Tire products - details'],
  [23,'wear','蓄电池系列 - 产品特点','Battery products - features'],
  [24,'wear','蓄电池系列 - 产品明细','Battery products - details'],
  [25,'wear','离合器从动盘系列 - 产品特点','Clutch disc products - features'],
  [26,'wear','离合器从动盘系列 - 产品明细（一）','Clutch disc products - details (I)'],
  [27,'wear','离合器从动盘系列 - 产品明细（二）','Clutch disc products - details (II)'],
  [28,'repair','维修件','Repair parts'],
  [29,'repair','发动机基础件系列 - 产品特点','Basic engine products - features'],
  [30,'repair','发动机基础件系列 - 产品明细（一）','Basic engine products - details (I)'],
  [31,'repair','发动机基础件系列 - 产品明细（二）','Basic engine products - details (II)'],
  [32,'repair','发动机基础件系列 - 产品明细（三）','Basic engine products - details (III)'],
  [33,'repair','发动机产品线 - 产品特点','Engine product line - features'],
  [34,'repair','发动机产品线 - 产品明细（一）','Engine product line - details (I)'],
  [35,'repair','发动机产品线 - 产品明细（二）','Engine product line - details (II)'],
  [36,'repair','发动机产品线 - 产品明细（三）','Engine product line - details (III)'],
  [37,'repair','发动机产品线 - 产品明细（四）','Engine product line - details (IV)'],
  [38,'repair','底盘产品系列 - 产品特点','Chassis products - features'],
  [39,'repair','底盘产品系列 - 产品明细（一）','Chassis products - details (I)'],
  [40,'repair','底盘产品系列 - 产品明细（二）','Chassis products - details (II)'],
  [41,'accident','事故件','Accident parts'],
  [42,'accident','驾驶室系列 - 产品特点','Cab products - features'],
  [43,'accident','驾驶室系列 - 产品明细','Cab products - details'],
  [44,'accident','车门 / 灯具 / 保险杠系列 - 产品特点','Door, lamp and bumper products - features'],
  [45,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（一）','Door, lamp and bumper products - details (I)'],
  [46,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（二）','Door, lamp and bumper products - details (II)'],
  [47,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（三）','Door, lamp and bumper products - details (III)'],
  [48,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（四）','Door, lamp and bumper products - details (IV)'],
  [49,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（五）','Door, lamp and bumper products - details (V)'],
  [50,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（六）','Door, lamp and bumper products - details (VI)'],
  [51,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（七）','Door, lamp and bumper products - details (VII)'],
  [52,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（八）','Door, lamp and bumper products - details (VIII)'],
  [53,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（九）','Door, lamp and bumper products - details (IX)'],
  [54,'accident','车门 / 灯具 / 保险杠系列 - 产品明细（十）','Door, lamp and bumper products - details (X)'],
  [55,'modification','改装件','Modification parts'],
  [56,'modification','改装件系列 - 产品特点','Modification products - features'],
  [57,'modification','改装件系列 - 产品明细（一）','Modification products - details (I)'],
  [58,'modification','改装件系列 - 产品明细（二）','Modification products - details (II)'],
  [59,'energy','新能源配件','New-energy parts'],
  [60,'energy','充电桩系列 - 产品特点','Charging pile products - features'],
  [61,'energy','充电桩系列 - 产品明细（一）','Charging pile products - details (I)'],
  [62,'energy','充电桩系列 - 产品明细（二）','Charging pile products - details (II)'],
  [63,'overview','产品手册封底','Manual back cover']
].map(([page,category,zh,en]) => ({page,category,zh,en,image:`assets/catalog/page-${String(page).padStart(2,'0')}.jpg`}));

const catalogCategories = {
  all: {zh:'全部 63 页',en:'All 63 pages'}, overview: {zh:'品牌与概览',en:'Brand & overview'},
  maintenance: {zh:'保养件',en:'Maintenance'}, wear: {zh:'易损件',en:'Wear parts'},
  repair: {zh:'维修件',en:'Repair parts'}, accident: {zh:'事故件',en:'Accident parts'},
  modification: {zh:'改装件',en:'Modification'}, energy: {zh:'新能源',en:'New energy'}
};
