'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=window.CATALOG, items=data.items, colors=['#3977cb','#dc9a2c','#6174a3','#b88598','#5eaaa0','#788ad7'];
let state={};try{state=JSON.parse(localStorage.getItem('automate-study-v1')||'{}')}catch{}if(!state||typeof state!=='object'||Array.isArray(state))state={};
let mode='catalog',cat='',page=1,selected=new Set(),filtered=[],toastTimer;
const getState=id=>state[id]||{}, norm=s=>String(s).toLowerCase().replace(/[\s（）()×*／/\-]/g,'');
const index=new Map(items.map(p=>[p.id,norm([p.name,p.originalName,p.code,p.type,p.categoryName,...Object.values(p.fields)].join(' '))]));
function notify(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,2500)}
function persist(){try{localStorage.setItem('automate-study-v1',JSON.stringify(state))}catch{notify('浏览器未允许保存，关闭后收藏可能丢失')}}
function setItem(id,key,value){state[id]={...getState(id),[key]:value};persist();updateStats()}
function toggleSave(id){setItem(id,'saved',!getState(id).saved);render();return getState(id).saved}
function updateStats(){$('#total').textContent=items.length.toLocaleString();const n=items.filter(x=>getState(x.id).saved).length;$('#saved-count').textContent=n;$('#favorite-total').innerHTML=n+'<small>条</small>';$('#image-count').innerHTML=items.filter(x=>x.image).length+'<small>条</small>'}
function drawCategories(){$('#categories').innerHTML=data.categories.map((c,i)=>`<button data-cat="${c.id}" class="${cat===c.id?'active':''}"><span class="category-dot" style="--cat:${colors[i]}"></span>${c.name}<b>${items.filter(p=>p.category===c.id).length}</b></button>`).join('')}
function drawTypes(){const old=$('#type').value,ts=[...new Set(items.filter(p=>!cat||p.category===cat).map(p=>p.type))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'zh'));$('#type').innerHTML='<option value="">全部产品</option>'+ts.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');if(ts.includes(old))$('#type').value=old}
function filter(){const q=$('#search').value.trim().split(/\s+/).filter(Boolean).map(norm),type=$('#type').value;filtered=items.filter(p=>(!cat||p.category===cat)&&(!type||p.type===type)&&(mode!=='saved'||getState(p.id).saved)&&q.every(t=>index.get(p.id).includes(t)));return filtered}
function mainSpec(p){if(p.category==='energy')return[p.fields['充电标准'],p.fields['功率'],p.fields['其他说明']].filter(Boolean).join(' · ');return p.application}
function render(){filter();updateStats();drawCategories();$('#scope-label').textContent=data.categories.find(c=>c.id===cat)?.name||'全部分类';const max=Math.max(1,Math.ceil(filtered.length/30));page=Math.min(page,max);$('#result-title').innerHTML=esc(cat?data.categories.find(c=>c.id===cat).name:mode==='saved'?'我的收藏':'全部产品')+` <span>${filtered.length} 条记录</span>`;$('#rows').innerHTML=filtered.slice((page-1)*30,page*30).map(p=>{const st=getState(p.id);return `<tr><td><input type="checkbox" aria-label="对比 ${esc(p.code)}" data-compare="${p.id}" ${selected.has(p.id)?'checked':''}></td><td class="photo-cell">${photo(p)}</td><td><button class="product-link" data-detail="${p.id}">${esc(p.name)}<span class="partcode">${esc(p.code)}</span></button></td><td><span class="pill">${p.categoryName}</span><span class="subtype">${esc(p.type)}</span></td><td class="app-cell"><span class="truncate">${esc(mainSpec(p))}</span></td><td><button class="star ${st.saved?'selected':''}" data-save="${p.id}" aria-label="${st.saved?'取消收藏':'收藏'} ${esc(p.code)}" aria-pressed="${!!st.saved}">${st.saved?'★':'☆'}</button></td></tr>`}).join('');$('#empty').hidden=filtered.length>0;$('#page-info').textContent=filtered.length?`显示 ${(page-1)*30+1}–${Math.min(page*30,filtered.length)} 条，共 ${filtered.length} 条`:'共 0 条';$('#page-number').textContent=`${page} / ${max}`;$('#prev').disabled=page<=1;$('#next').disabled=page>=max}
function setMode(m){mode=m;page=1;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#page-title').innerHTML=m==='saved'?'我的收藏<span>SAVED</span>':'产品清单<span>CATALOG</span>';$('#page-desc').textContent=m==='saved'?'常用的配件，随时找到。':'从名称、配件图号或适用车型开始查找。';render()}
function reset(){cat='';$('#search').value='';$('#type').value='';drawTypes();page=1;render()}
function detail(id){const p=items.find(p=>p.id===id);if(!p)return;$('#dialog-caption').textContent='产品详情';$('#detail-content').innerHTML=`<span class="pill">${p.categoryName} / ${esc(p.type)}</span><h2 class="detail-title">${esc(p.name)}</h2><div class="partcode">${esc(p.code)}</div>${p.needsReview?'<p class="review-notice">部分文字识别待核对，请以原始手册为准。</p>':''}<div class="detail-photo">${photo(p,true)}</div><div class="detail-actions"><button class="primary" data-detail-save="${p.id}">${getState(id).saved?'★ 已收藏':'☆ 收藏产品'}</button><button class="secondary" data-copy="${id}">复制配件图号</button></div><dl>${Object.entries(p.fields).filter(([k,v])=>v&&v!=='/').map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p class="detail-foot">来源：产品手册第 ${p.page} 页（印刷页码 ${p.printedPage}）<br>“手册未注明”表示原文没有提供该字段。当前为手册资料清单，不含实时价格与库存。</p><a class="text-button" href="assets/FOTON-AUTOMATE-product-manual.pdf#page=${p.page}" target="_blank" rel="noopener">核对原始出处 ↗</a>`;if(!$('#detail').open)$('#detail').showModal()}
function compareBar(){$('#compare-bar').hidden=!selected.size;$('#compare-count').textContent=`已选 ${selected.size} / 3 项`;$('#compare-open').disabled=selected.size<2}
function showCompare(){const ps=items.filter(p=>selected.has(p.id));const keys=[...new Set(ps.flatMap(p=>Object.keys(p.fields)))];$('#dialog-caption').textContent='产品对比';$('#detail-content').innerHTML=`<h2 class="detail-title">把区别放在一起看</h2><div class="table-wrap"><table class="compare-table"><thead><tr><th>字段</th>${ps.map(p=>`<th>${esc(p.name)}<span class="partcode">${esc(p.code)}</span></th>`).join('')}</tr></thead><tbody>${keys.map(k=>`<tr><td>${esc(k)}</td>${ps.map(p=>`<td>${esc(p.fields[k]||'手册未注明')}</td>`).join('')}</tr>`).join('')}<tr><td>手册页</td>${ps.map(p=>`<td>第 ${p.page} 页</td>`).join('')}</tr></tbody></table></div>`;$('#detail').showModal()}
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;cat=cat===b.dataset.cat?'':b.dataset.cat;$('#type').value='';drawTypes();page=1;render()});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#reset-cat').onclick=()=>{cat='';drawTypes();page=1;render()};$('#clear').onclick=reset;$('#empty-reset').onclick=reset;
for(const selector of ['#search','#type'])$(selector).addEventListener(selector==='#search'?'input':'change',()=>{page=1;render()});
$('#rows').addEventListener('click',e=>{const d=e.target.closest('[data-detail]'),s=e.target.closest('[data-save]');if(d)detail(d.dataset.detail);if(s)toggleSave(s.dataset.save)});
$('#rows').addEventListener('change',e=>{const id=e.target.dataset.compare;if(!id)return;if(e.target.checked){if(selected.size===3){e.target.checked=false;notify('最多选择 3 个产品进行对比');return}selected.add(id)}else selected.delete(id);compareBar()});
$('#prev').onclick=()=>{page--;render()};$('#next').onclick=()=>{page++;render()};$('#close-detail').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close()}});
$('#detail-content').addEventListener('click',async e=>{const s=e.target.closest('[data-detail-save]'),c=e.target.closest('[data-copy]');if(s){toggleSave(s.dataset.detailSave);detail(s.dataset.detailSave)}if(c){try{await navigator.clipboard.writeText(items.find(p=>p.id===c.dataset.copy).code);notify('配件图号已复制')}catch{notify('无法自动复制，请选中图号复制')}}});
$('#compare-open').onclick=showCompare;$('#compare-clear').onclick=()=>{selected.clear();compareBar();render()};

document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('#detail').open){e.preventDefault();$('#search').focus()}});
function photo(p,large=false){return p.image?`<figure class="part-photo ${large?'large':''}"><img src="${esc(p.image)}" alt="${esc(p.type)}系列示意图，非图号专属照片" loading="lazy"><figcaption>系列示意图${large?' · 手册第 '+p.imagePage+' 页':''}</figcaption></figure>`:'<div class="no-photo">暂无对应图片</div>'}
drawTypes();render();
